[platformio]
default_envs = esp32dev

[env:base]
platform = espressif32
board = esp32dev
framework = arduino
board_build.f_flash = 80000000L
board_build.flash_mode = dio
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.2
    etlcpp/Embedded Template Library @ ^20.40.0
    nanopb/Nanopb@^0.4.9
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder
build_flags =
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED=1
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER_DISABLED=1
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -DCONFIG_BT_NIMBLE_MSYS_1_BLOCK_COUNT=6
    -DCONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE=4096
    -DECB_V5_ENABLED=1
    -DPB_FIELD_32BIT=1
extra_scripts =
    pre:tools/gen_manifest.py
    pre:tools/gen_nanopb_v5.py

[env:esp32dev]
extends = env:base
build_flags =
    ${env:base.build_flags}
    -DCORE_DEBUG_LEVEL=3

[env:release]
extends = env:base
build_type = release
build_flags =
    ${env:base.build_flags}
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_LOG_DEFAULT_LEVEL=2
    -O2

[env:native]
platform = native
build_flags = -std=c++11
lib_deps =
test_ignore = test_embedded_*
