import { Type, type Static } from '@sinclair/typebox';

const FIRMWARE_RESERVED_KEYWORDS = [
  'alignas',
  'alignof',
  'and',
  'and_eq',
  'asm',
  'atomic_cancel',
  'atomic_commit',
  'atomic_noexcept',
  'auto',
  'bitand',
  'bitor',
  'bool',
  'break',
  'case',
  'catch',
  'char',
  'char8_t',
  'char16_t',
  'char32_t',
  'class',
  'compl',
  'concept',
  'const',
  'consteval',
  'constexpr',
  'constinit',
  'const_cast',
  'continue',
  'co_await',
  'co_return',
  'co_yield',
  'decltype',
  'default',
  'delete',
  'do',
  'double',
  'dynamic_cast',
  'else',
  'enum',
  'explicit',
  'export',
  'extern',
  'false',
  'final',
  'float',
  'for',
  'friend',
  'goto',
  'if',
  'import',
  'inline',
  'int',
  'long',
  'module',
  'mutable',
  'namespace',
  'new',
  'noexcept',
  'not',
  'not_eq',
  'nullptr',
  'operator',
  'or',
  'or_eq',
  'override',
  'private',
  'protected',
  'public',
  'reflexpr',
  'register',
  'reinterpret_cast',
  'requires',
  'return',
  'short',
  'signed',
  'sizeof',
  'static',
  'static_assert',
  'static_cast',
  'struct',
  'switch',
  'synchronized',
  'template',
  'this',
  'thread_local',
  'throw',
  'true',
  'try',
  'typedef',
  'typeid',
  'typename',
  'union',
  'unsigned',
  'using',
  'virtual',
  'void',
  'volatile',
  'wchar_t',
  'while',
  'xor',
  'xor_eq',
] as const;

const FIRMWARE_RESERVED_KEYWORD_PATTERN = FIRMWARE_RESERVED_KEYWORDS.join('|');

export const SlugId = Type.String({
  pattern: '^[a-z][a-z0-9_]*(\\.[a-z0-9_]+)*$',
  minLength: 1,
  maxLength: 48,
});
export type SlugId = Static<typeof SlugId>;

export const Label = Type.String({
  minLength: 1,
  maxLength: 64,
});
export type Label = Static<typeof Label>;

export const TokenRef = Type.String({
  pattern: '^[a-z][a-z0-9_]*\\.[a-z0-9_]+$',
  minLength: 3,
  maxLength: 48,
});
export type TokenRef = Static<typeof TokenRef>;

export const FirmwareSymbol = Type.String({
  minLength: 1,
  maxLength: 64,
  pattern: `^(?!(?:${FIRMWARE_RESERVED_KEYWORD_PATTERN})$)[a-z][a-z0-9_]*$`,
});
export type FirmwareSymbol = Static<typeof FirmwareSymbol>;
