"""PlatformIO pre-build step: emit the manifest from C++ with NO Node.

Replaces the legacy YAML -> Node/protobuf path (tools/embed_manifest.py). Compiles
a tiny host program (tools/ui_emit_main.cpp + the device description + the
esp-control-ble UI emitter + vendored nanopb) with the SAME mingw host g++ the
native tests use, then runs it. The program writes:
    src/generated/manifest_data.h  (the embedded protobuf; byte-identical to the
                                    old TS-generated bytes -- the tablet sees no change)

Requires the checked-in nanopb headers (produced by gen_nanopb.py, which must run
BEFORE this script) and the native nanopb runtime under .pio/libdeps/native/Nanopb.
On any compile/run failure this FAILS the build loudly -- it never silently falls
back to stale generated headers (that would hide manifest drift).
"""
Import("env")  # noqa: F821  (PlatformIO injects it)
from pathlib import Path
import os
import shutil
import subprocess
import sys

PROJECT = Path(env["PROJECT_DIR"])
LIB_SRC = PROJECT / "lib" / "esp-control-ble" / "src"
NANOPB_GEN = LIB_SRC / "nanopb"            # checked-in manifest.pb.h (+ pb headers via runtime)
SRC_OUT = PROJECT / "src" / "generated"    # destination for the generated header
BUILD_CACHE = PROJECT / "build_cache"
EXE = BUILD_CACHE / ("ui_emit.exe" if sys.platform == "win32" else "ui_emit")

# Host nanopb runtime (pb_encode.c / pb_common.c / pb_encode.h ...). Same vendored
# copy the native tests link.
NANOPB_RUNTIME = PROJECT / ".pio" / "libdeps" / "native" / "Nanopb"

# Translation units compiled into the host emitter. HwHal.cpp is included because
# the device description may call ecb::ui::halAnalogWrite / halDigitalWrite from a
# .onSet handler (the demo drives an LED that way). Under -DECB_HOST_EMIT its body is
# a guarded no-op (no Arduino), so it only satisfies the link -- it never touches HW
# at emit time, and EmitterUi ignores .onSet anyway, so the emitted bytes are unaffected.
SOURCES = [
    PROJECT / "tools" / "ui_emit_main.cpp",
    PROJECT / "src" / "device_ui.cpp",
    LIB_SRC / "ui" / "EmitterUi.cpp",
    LIB_SRC / "ui" / "UiModelEncoder.cpp",
    LIB_SRC / "ui" / "HwHal.cpp",
]


def resolve_gxx():
    """Locate the host g++. Returns (gxx_path, toolchain_bin_dir_or_None).

    toolchain_bin_dir is the mingw .../bin we must put FIRST on PATH so the
    compiler's own helper processes (cc1plus.exe, collect2.exe) load THIS
    toolchain's runtime DLLs -- see controlled_env() for why that matters.
    """
    # Preferred: the toolchain PlatformIO already installed for the native env.
    try:
        pkg_dir = env.PioPlatform().get_package_dir("toolchain-gccmingw32")
        if pkg_dir:
            candidate = Path(pkg_dir) / "bin" / "g++.exe"
            if candidate.is_file():
                return str(candidate), candidate.parent
    except Exception:
        pass
    # Fallback: the conventional core packages location.
    core_candidate = Path.home() / ".platformio" / "packages" / "toolchain-gccmingw32" / "bin" / "g++.exe"
    if core_candidate.is_file():
        return str(core_candidate), core_candidate.parent
    # Last resort: a system g++ on PATH (non-Windows hosts).
    found = shutil.which("g++")
    if found:
        return found, None
    print("[emit_ui] no host g++ found (toolchain-gccmingw32 or system g++)", file=sys.stderr)
    sys.exit(1)


def controlled_env(toolchain_bin):
    """Run g++ with the mingw toolchain's own dirs FIRST on PATH.

    PlatformIO prepends other toolchains (notably toolchain-xtensa-esp32, an
    x86_64-SEH mingw build) to PATH before invoking pre-build scripts. Our host
    g++ is the 32-bit i686-dw2 toolchain-gccmingw32; its helper exes (cc1plus,
    collect2) are dynamically linked and resolve libstdc++-6 / libgcc_s /
    libwinpthread by PATH order. If the xtensa bin is found first, they load a
    mismatched-arch DLL and crash at load with STATUS_STACK_BUFFER_OVERRUN
    (0xC0000409) and NO output -- intermittently, depending on PATH. Putting the
    mingw bin (and its i686-w64-mingw32/lib DLL dir) at the front makes the right
    DLLs win deterministically. ``-static`` only affects the EMITTED exe, not the
    compiler's own processes, so it does not help here.
    """
    if toolchain_bin is None:
        return None  # system g++ (non-Windows): inherit env unchanged.
    env_copy = dict(os.environ)
    dll_dir = toolchain_bin.parent / "i686-w64-mingw32" / "lib"  # libgcc_s_dw2 / libstdc++-6 / libwinpthread
    front = [str(toolchain_bin)]
    if dll_dir.is_dir():
        front.append(str(dll_dir))
    env_copy["PATH"] = os.pathsep.join(front + [env_copy.get("PATH", "")])
    return env_copy


def writable_exe_path() -> Path:
    """Return a path the linker can write the host emitter to.

    The linker cannot overwrite an .exe that is currently open (a transient
    AV scan or a zombie process holding build_cache/ui_emit.exe makes g++ fail
    to write the output -- on mingw that surfaces as a non-zero exit with NO
    diagnostic, an opaque "host compile failed" with empty output). So delete a
    stale target up front; if it is locked, fall back to a uniquely-named exe so
    the build still succeeds instead of dying on a file lock.
    """
    if EXE.exists():
        try:
            EXE.unlink()
            return EXE
        except OSError:
            # Locked (AV / open handle): use a distinct name this run.
            alt = BUILD_CACHE / ("ui_emit_%d%s" % (os.getpid(), EXE.suffix))
            print(
                "[emit_ui] %s is locked (open handle / AV?); emitting to %s instead"
                % (EXE.name, alt.name),
                file=sys.stderr,
            )
            return alt
    return EXE


# Windows NTSTATUS failures (e.g. 0xC0000409 STATUS_STACK_BUFFER_OVERRUN,
# 0xC0000005 access violation) come back from subprocess as huge unsigned-looking
# exit codes >= 0xC0000000. Those mean a process CRASHED (a host-environment
# problem: a DLL mismatch, a Defender real-time hook killing cc1plus, a transient
# file lock) -- NOT a compile error (g++ returns 1/4 WITH diagnostics for those).
# Crashes here are intermittent, so a retry clears them; a real compile error is
# deterministic and must fail fast.
def _is_crash_code(code):
    return code is not None and (code & 0xFFFFFFFF) >= 0xC0000000


def run_with_retry(cmd, run_env, what, attempts=4):
    """subprocess.run, retrying only on a crash exit code (not on compile errors)."""
    last = None
    for attempt in range(1, attempts + 1):
        last = subprocess.run(cmd, capture_output=True, text=True, env=run_env)
        if last.returncode == 0 or not _is_crash_code(last.returncode):
            return last
        print(
            "[emit_ui] %s crashed (exit 0x%08X) on attempt %d/%d -- retrying"
            % (what, last.returncode & 0xFFFFFFFF, attempt, attempts),
            file=sys.stderr,
        )
    return last


def main():
    BUILD_CACHE.mkdir(exist_ok=True)
    SRC_OUT.mkdir(parents=True, exist_ok=True)

    for source in SOURCES:
        if not source.is_file():
            print(f"[emit_ui] missing source {source}", file=sys.stderr)
            sys.exit(1)

    if not (NANOPB_RUNTIME / "pb_encode.c").is_file() or not (NANOPB_RUNTIME / "pb_common.c").is_file():
        print(
            f"[emit_ui] nanopb runtime not found at {NANOPB_RUNTIME}\n"
            f"[emit_ui] (run the native env once so PlatformIO vendors Nanopb, or build esp32dev "
            f"after gen_nanopb.py)",
            file=sys.stderr,
        )
        sys.exit(1)

    gxx, toolchain_bin = resolve_gxx()
    run_env = controlled_env(toolchain_bin)
    exe = writable_exe_path()

    cmd = [
        gxx,
        "-std=gnu++14", "-O2",
        "-static", "-static-libgcc", "-static-libstdc++",
        "-DPB_FIELD_32BIT",
        "-DECB_HOST_EMIT",
        "-I", str(LIB_SRC),
        "-I", str(NANOPB_GEN),
        "-I", str(NANOPB_RUNTIME),
        "-I", str(PROJECT / "src"),
    ]
    cmd += [str(s) for s in SOURCES]
    cmd += [str(NANOPB_RUNTIME / "pb_encode.c"), str(NANOPB_RUNTIME / "pb_common.c")]
    cmd += ["-o", str(exe)]

    print("[emit_ui] compiling host emitter:")
    print("[emit_ui]   " + " ".join(cmd))
    result = run_with_retry(cmd, run_env, "host compile")
    if result.returncode != 0:
        # Always surface the exit code: a linker that cannot write the .exe can
        # fail with no stdout/stderr, and a bare "host compile failed" with empty
        # output is impossible to diagnose.
        detail = (result.stdout + result.stderr).strip() or "(no compiler output)"
        crash = " [crash, not a compile error]" if _is_crash_code(result.returncode) else ""
        print(
            "[emit_ui] host compile failed (g++ exit 0x%08X)%s:\n%s"
            % (result.returncode & 0xFFFFFFFF, crash, detail),
            file=sys.stderr,
        )
        sys.exit(1)
    if result.stderr.strip():
        print(result.stderr.strip())

    print(f"[emit_ui] running {exe.name} -> {SRC_OUT}")
    run = subprocess.run([str(exe), str(SRC_OUT)], capture_output=True, text=True, env=run_env)
    if run.returncode != 0:
        detail = (run.stdout + run.stderr).strip() or "(no emitter output)"
        print(
            f"[emit_ui] emitter run failed (exit {run.returncode}):\n{detail}",
            file=sys.stderr,
        )
        sys.exit(1)
    print(run.stdout.strip())


main()
