"""PlatformIO pre-build step: emit the manifest from C++ with NO Node.

Replaces the legacy YAML -> Node/protobuf path (tools/embed_manifest.py). Compiles
a tiny host program (tools/ui_emit_main.cpp + the device description + the
esp-control-ble UI emitter + vendored nanopb) with the SAME mingw host g++ the
native tests use, then runs it. The program writes:
    src/manifest_data.h       (the embedded protobuf; byte-identical to the old
                               TS-generated bytes -- the tablet sees no change)
    src/manifest_symbols.h    (slug -> id symbol tables, declarations)
    src/manifest_symbols.cpp  (slug -> id symbol tables, definitions)

Requires the checked-in nanopb headers (produced by gen_nanopb.py, which must run
BEFORE this script) and the native nanopb runtime under .pio/libdeps/native/Nanopb.
On any compile/run failure this FAILS the build loudly -- it never silently falls
back to stale generated headers (that would hide manifest drift).
"""
Import("env")  # noqa: F821  (PlatformIO injects it)
from pathlib import Path
import shutil
import subprocess
import sys

PROJECT = Path(env["PROJECT_DIR"])
LIB_SRC = PROJECT / "lib" / "esp-control-ble" / "src"
NANOPB_GEN = LIB_SRC / "nanopb"            # checked-in manifest.pb.h (+ pb headers via runtime)
SRC_OUT = PROJECT / "src"                  # destination for the generated headers
BUILD_CACHE = PROJECT / "build_cache"
EXE = BUILD_CACHE / ("ui_emit.exe" if sys.platform == "win32" else "ui_emit")

# Host nanopb runtime (pb_encode.c / pb_common.c / pb_encode.h ...). Same vendored
# copy the native tests link.
NANOPB_RUNTIME = PROJECT / ".pio" / "libdeps" / "native" / "Nanopb"

# Translation units compiled into the host emitter.
SOURCES = [
    PROJECT / "tools" / "ui_emit_main.cpp",
    PROJECT / "app" / "device" / "device_ui.cpp",
    LIB_SRC / "ui" / "EmitterUi.cpp",
    LIB_SRC / "ui" / "UiModelEncoder.cpp",
]


def resolve_gxx() -> str:
    """Locate the host g++: the PlatformIO mingw toolchain on Windows, else system g++."""
    # Preferred: the toolchain PlatformIO already installed for the native env.
    try:
        pkg_dir = env.PioPlatform().get_package_dir("toolchain-gccmingw32")
        if pkg_dir:
            candidate = Path(pkg_dir) / "bin" / "g++.exe"
            if candidate.is_file():
                return str(candidate)
    except Exception:
        pass
    # Fallback: the conventional core packages location.
    core_candidate = Path.home() / ".platformio" / "packages" / "toolchain-gccmingw32" / "bin" / "g++.exe"
    if core_candidate.is_file():
        return str(core_candidate)
    # Last resort: a system g++ on PATH (non-Windows hosts).
    found = shutil.which("g++")
    if found:
        return found
    print("[emit_ui] no host g++ found (toolchain-gccmingw32 or system g++)", file=sys.stderr)
    sys.exit(1)


def main():
    BUILD_CACHE.mkdir(exist_ok=True)

    for source in SOURCES:
        if not source.is_file():
            print(f"[emit_ui] missing source {source}", file=sys.stderr)
            sys.exit(1)

    if not (NANOPB_RUNTIME / "pb_encode.c").is_file() or not (NANOPB_RUNTIME / "pb_common.c").is_file():
        print(
            f"[emit_ui] nanopb runtime not found at {NANOPB_RUNTIME}\n"
            f"[emit_ui] (run the native env once so PlatformIO vendors Nanopb, or build esp32dev "
            f"after gen_nanopb.py)",
            file=sys.stderr,
        )
        sys.exit(1)

    gxx = resolve_gxx()

    cmd = [
        gxx,
        "-std=gnu++14", "-O2",
        "-static", "-static-libgcc", "-static-libstdc++",
        "-DPB_FIELD_32BIT",
        "-I", str(LIB_SRC),
        "-I", str(NANOPB_GEN),
        "-I", str(NANOPB_RUNTIME),
        "-I", str(PROJECT / "app"),
        "-I", str(SRC_OUT),
    ]
    cmd += [str(s) for s in SOURCES]
    cmd += [str(NANOPB_RUNTIME / "pb_encode.c"), str(NANOPB_RUNTIME / "pb_common.c")]
    cmd += ["-o", str(EXE)]

    print("[emit_ui] compiling host emitter:")
    print("[emit_ui]   " + " ".join(cmd))
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"[emit_ui] host compile failed:\n{result.stdout}\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    if result.stderr.strip():
        print(result.stderr.strip())

    print(f"[emit_ui] running {EXE.name} -> {SRC_OUT}")
    run = subprocess.run([str(EXE), str(SRC_OUT)], capture_output=True, text=True)
    if run.returncode != 0:
        print(f"[emit_ui] emitter run failed:\n{run.stdout}\n{run.stderr}", file=sys.stderr)
        sys.exit(1)
    print(run.stdout.strip())


main()
