/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "manifest_v5.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif


/* The following messages exceed 64kB in size: esp_control_v5_ManifestBundleV5 */

/* The PB_FIELD_32BIT compilation option must be defined to support messages that exceed 64 kB in size. */
#ifndef PB_FIELD_32BIT
#error Enable PB_FIELD_32BIT to support messages exceeding 64kB in size: esp_control_v5_ManifestBundleV5
#endif
PB_BIND(esp_control_v5_StringEntry, esp_control_v5_StringEntry, AUTO)


PB_BIND(esp_control_v5_Rule, esp_control_v5_Rule, 2)


PB_BIND(esp_control_v5_CapabilitiesDef, esp_control_v5_CapabilitiesDef, AUTO)


PB_BIND(esp_control_v5_ResourceDef, esp_control_v5_ResourceDef, AUTO)


PB_BIND(esp_control_v5_ActionDef, esp_control_v5_ActionDef, AUTO)


PB_BIND(esp_control_v5_ScreenDef, esp_control_v5_ScreenDef, 2)


PB_BIND(esp_control_v5_BindingDef, esp_control_v5_BindingDef, AUTO)


PB_BIND(esp_control_v5_NodeDef, esp_control_v5_NodeDef, 2)


PB_BIND(esp_control_v5_ManifestBundleV5, esp_control_v5_ManifestBundleV5, 4)


PB_BIND(esp_control_v5_ResourceValue, esp_control_v5_ResourceValue, AUTO)


PB_BIND(esp_control_v5_ResourceSnapshot, esp_control_v5_ResourceSnapshot, 4)


PB_BIND(esp_control_v5_ResourceDelta, esp_control_v5_ResourceDelta, AUTO)


PB_BIND(esp_control_v5_InvokeAction, esp_control_v5_InvokeAction, AUTO)


PB_BIND(esp_control_v5_InvokeResult, esp_control_v5_InvokeResult, AUTO)


PB_BIND(esp_control_v5_Subscribe, esp_control_v5_Subscribe, 2)


PB_BIND(esp_control_v5_Unsubscribe, esp_control_v5_Unsubscribe, 2)















