/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "manifest.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif


/* The following messages exceed 64kB in size: esp_control_ManifestBundle */

/* The PB_FIELD_32BIT compilation option must be defined to support messages that exceed 64 kB in size. */
#ifndef PB_FIELD_32BIT
#error Enable PB_FIELD_32BIT to support messages exceeding 64kB in size: esp_control_ManifestBundle
#endif
PB_BIND(esp_control_StringEntry, esp_control_StringEntry, AUTO)


PB_BIND(esp_control_Rule, esp_control_Rule, 2)


PB_BIND(esp_control_CommonField, esp_control_CommonField, AUTO)


PB_BIND(esp_control_CommonObject, esp_control_CommonObject, AUTO)


PB_BIND(esp_control_CommonList, esp_control_CommonList, AUTO)


PB_BIND(esp_control_CommonValue, esp_control_CommonValue, AUTO)


PB_BIND(esp_control_CapabilitiesDef, esp_control_CapabilitiesDef, AUTO)


PB_BIND(esp_control_ResourceDef, esp_control_ResourceDef, AUTO)


PB_BIND(esp_control_ActionDef, esp_control_ActionDef, AUTO)


PB_BIND(esp_control_ScreenDef, esp_control_ScreenDef, 2)


PB_BIND(esp_control_BindingDef, esp_control_BindingDef, AUTO)


PB_BIND(esp_control_NodeDef, esp_control_NodeDef, 2)


PB_BIND(esp_control_ManifestBundle, esp_control_ManifestBundle, 4)


PB_BIND(esp_control_ResourceValue, esp_control_ResourceValue, AUTO)


PB_BIND(esp_control_ResourceSnapshot, esp_control_ResourceSnapshot, AUTO)


PB_BIND(esp_control_ResourceDelta, esp_control_ResourceDelta, AUTO)


PB_BIND(esp_control_InvokeAction, esp_control_InvokeAction, AUTO)


PB_BIND(esp_control_InvokeResult, esp_control_InvokeResult, AUTO)


PB_BIND(esp_control_Subscribe, esp_control_Subscribe, AUTO)


PB_BIND(esp_control_Unsubscribe, esp_control_Unsubscribe, AUTO)















